"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the plugin `status-bar`"
permissions = [
  "allow-hide",
  "allow-is-visible",
  "allow-set-status-bar",
  "allow-default-scroll-top",
  "allow-registerListener",
]
